<a href="https://colab.research.google.com/github/jimmy10107/NLP_100days_Part1/blob/main/%E8%AA%8D%E8%AD%98_Pytorch_%E7%9A%84%E5%BC%B5%E9%87%8F%E8%88%87%E5%85%B6%E5%9F%BA%E6%9C%AC%E6%93%8D%E4%BD%9C_%E4%BD%9C%E6%A5%AD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

In [1]:
# Import torch and other required modules
import torch
import numpy as np

In [6]:
# 0維tensor (scalar)
t1 = torch.tensor(1, dtype=torch.int16)
print(t1.shape)
t1

# 1維tensor (vector)
t2 = torch.tensor([1,2,3], dtype=torch.float32)
print(t2.shape)
t2

# 2維tensor (matrix)
t3 = torch.tensor([[1.,2],[3,4]])
print(t3.shape)
t3

# 3維tensor (n-dimensional array)
t4 = torch.tensor([[[1, 2, 3], [3, 4, 5]],
					[[5, 6, 7], [7, 8 ,9]]])
print(t4.shape)
t4

# torch.randn: 由平均值為0，標準差為1的常態分佈中，抽樣元素組成給定形狀的張量
t5 = torch.randn((2,3,5))
print(t5.shape)
t5

# torch.randint: 在給定的上下界(預設下界為0)中抽樣"整數"元素組成給定形狀的張量
t6 = torch.randint(low=0, high=10, size=(3,2))
print(t6.shape)
t6

# torch.ones: 產生給定形狀，元素全為1的張量
t7 = torch.ones((2,3))
print(t7.shape)
t7

# torch.ones_like: 產生與給定張量相同形狀，但元素全為1的張量
t8 = torch.ones_like(t6)
print(t8.shape)
t8

torch.Size([])
torch.Size([3])
torch.Size([2, 2])
torch.Size([2, 2, 3])
torch.Size([2, 3, 5])
torch.Size([3, 2])
torch.Size([2, 3])
torch.Size([3, 2])


tensor([[1, 1],
        [1, 1],
        [1, 1]])

In [8]:
# 產生numpy ndarray
x = np.array([[1.,2],[3,4]])
print(x.shape)
x

# 由numpy ndarray產生pytorch tensor
y = torch.from_numpy(x)
# y = torch.tensor(x) 也可以達到同樣效果
print(y.shape)
y

# 檢查array與tensor的資料型態
x.dtype, y.dtype

# 將tensor轉換為array
z = y.numpy()
print(z.shape)
z

(2, 2)
torch.Size([2, 2])
(2, 2)


array([[1., 2.],
       [3., 4.]])

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [2]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [ ]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int64
b: <class 'torch.Tensor'>, torch.int64
c: <class 'torch.Tensor'>, torch.int64
d: <class 'numpy.ndarray'>, int64


### Function 1 - *your function to illustrate*

In [9]:
# 創建tensor
a = torch.randn((2,3))
b = torch.randn(3)
print(a.shape, b.shape)
a, b

# 相加
t_add1 = a + b
t_add2 = torch.add(a,b)
print(t_add1.shape, t_add2.shape)
t_add1, t_add2

# 相減
t_sub1 = a - b
t_sub2 = torch.sub(a,b)
print(t_sub1.shape, t_sub2.shape)
t_sub1, t_sub2

# 相除
t_div1 = a / b
t_div2 = torch.div(a,b)
print(t_div1.shape, t_div2.shape)
t_div1, t_div2

# 相乘
t_mul1 = a * b
t_mul2 = torch.mul(a, b)
print(t_mul1.shape, t_mul2.shape)
t_mul1, t_mul2

# 矩陣乘法
c = torch.randn((2,3))
d = torch.randn((3,4))

t_matmul1 = c.mm(d)
t_matmul2 = torch.mm(c,d)
t_matmul3 = torch.matmul(c,d)
t_matmul4 = c @ d

print(t_matmul1,shape, t_matmul2,shape, t_matmul3,shape, t_matmul4,shape)

In [ ]:
# Example 2 - ### your explanation ###
### your code ###

### Function 2 - your function to illustrate

In [10]:
# 創健tensor
a = torch.tensor([[[1, 2, 3], [3, 4, 5]],
									[[5, 6, 7], [7, 8, 9]]])
print(a.shape)
print(a)

# 將tensor形狀由[2,2,3]改為[2,6]
b = a.reshape(2, 6)
c = a.view(2, 6)
d = a.reshape(2, -1)
print(b.shape, c.shape, d.shape)
b,c,d

# 調換tensor維度
e = a.permute((0, 2, 1))
f = a.transpose(1,2)
print(e.shape, f.shape)
e, f

# 增加張量維度
g = torch.unsqueeze(a, dim=1) #增加維度在1的位置
h = torch.squeeze(g) #壓縮為度為1的位置
print(g.shape, h.shape)

torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [3, 4, 5]],

        [[5, 6, 7],
         [7, 8, 9]]])
torch.Size([2, 6]) torch.Size([2, 6]) torch.Size([2, 6])
torch.Size([2, 3, 2]) torch.Size([2, 3, 2])
torch.Size([2, 1, 2, 3]) torch.Size([2, 2, 3])
